services:
  - type: web
    name: proxy-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: "8000"
    plan: free
    autoDeploy: true
    healthCheckPath: /health
