services:
  - type: web
    name: sim-card-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: 8897748741:AAG2f8sHicGX_wxGEBPm2gqgbULhkGp4weE
      - key: ADMIN_CHAT_ID
        value: 5979001063
